# Generated by Django 3.0.8 on 2020-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcoffee',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
