# Generated by Django 3.0.8 on 2020-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200708_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcard',
            name='bonus_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, null=True),
        ),
    ]
