# Generated by Django 3.0.8 on 2020-07-08 07:51

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=18, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoughtCoffee',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee', to='discount.Coffee')),
            ],
        ),
    ]
