# Generated by Django 3.0.8 on 2020-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_boughtcoffee_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcoffee',
            name='with_card',
            field=models.BooleanField(default=True),
        ),
    ]
