# Generated by Django 3.0.8 on 2020-07-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200708_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal', to='account.DiscountCard'),
        ),
    ]
