# Generated by Django 3.0.8 on 2020-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200708_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='barcode',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
